# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  build:
    description: Builds the project
    cmds:
      - cc main.c myutils.c
  run:
    cmds:
      - task: build
      - ./a.out
      - rm a.out
